export const abi =  [
    {
        inputs: [
            { internalType: 'address[5]', name: '_addrs', type: 'address[5]' },
            { internalType: 'uint256', name: '_rateSetting', type: 'uint256' },
            { internalType: 'uint256[2]', name: '_decimals', type: 'uint256[2]' },
            { internalType: 'uint256[2]', name: '_contributionSettings', type: 'uint256[2]' },
            { internalType: 'uint256[2]', name: '_capSettings', type: 'uint256[2]' },
            { internalType: 'uint256[2]', name: '_timeSettings', type: 'uint256[2]' },
            { internalType: 'bool', name: '_useWhitelisting', type: 'bool' },
            { internalType: 'string', name: '_poolDetails', type: 'string' },
            { internalType: 'uint256[2]', name: '_withdrawArg', type: 'uint256[2]' },
            { internalType: 'uint256', name: '_lockSeconds', type: 'uint256' },
            { internalType: 'uint256[2]', name: '_swapAmounts', type: 'uint256[2]' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'pair', type: 'address' },
            { indexed: !1, internalType: 'address', name: 'tokenA', type: 'address' },
            { indexed: !1, internalType: 'address', name: 'tokenB', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amountA', type: 'uint256' },
            { indexed: !1, internalType: 'uint256', name: 'amountB', type: 'uint256' },
        ],
        name: 'AddLiquidity',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [{ indexed: !1, internalType: 'address[]', name: '_usersAddresses', type: 'address[]' }],
        name: 'AddMultiWhitelistedUsers',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'BurnToken',
        type: 'event',
    },
    { anonymous: !1, inputs: [{ indexed: !1, internalType: 'address', name: 'sender', type: 'address' }], name: 'Cancel', type: 'event' },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'recipient', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'Claim',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'value', type: 'uint256' },
        ],
        name: 'Contribute',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'ContributionerWithdraw',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'DistributePurchasedTokens',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'DistributeRefund',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'Finalize',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'uniswapPair', type: 'address' },
            { indexed: !1, internalType: 'address', name: 'lockOwner', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
            { indexed: !1, internalType: 'uint256', name: 'lockTimeStamp', type: 'uint256' },
            { indexed: !1, internalType: 'uint256', name: 'lockSeconds', type: 'uint256' },
        ],
        name: 'Lock',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !0, internalType: 'address', name: 'previousOwner', type: 'address' },
            { indexed: !0, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [{ indexed: !1, internalType: 'address[]', name: '_usersAddresses', type: 'address[]' }],
        name: 'RemoveMultiWhitelistedUsers',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'uniswapPair', type: 'address' },
            { indexed: !1, internalType: 'address', name: 'nowOwner', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
            { indexed: !1, internalType: 'uint256', name: 'unlockTimeStamp', type: 'uint256' },
        ],
        name: 'Unlock',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'Withdraw',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
            { indexed: !1, internalType: 'uint256', name: 'tokenAmount', type: 'uint256' },
        ],
        name: 'WithdrawCancel',
        type: 'event',
    },
    {
        anonymous: !1,
        inputs: [
            { indexed: !1, internalType: 'address', name: 'sender', type: 'address' },
            { indexed: !1, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'WithdrawToken',
        type: 'event',
    },
    { stateMutability: 'payable', type: 'fallback' },
    { inputs: [], name: 'FomoAmount', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'FomoRate', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [{ internalType: 'address[]', name: '_usersAddresses', type: 'address[]' }],
        name: 'addMultiWhitelistedUsers',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'additionalInfo', outputs: [{ internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'cancel', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'claim', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'address', name: '_recommend', type: 'address' }],
        name: 'contribute',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'contributionAmount',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'contributionIsClaim',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'contributionIsRefund',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'contributionList',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_amount', type: 'uint256' }],
        name: 'contributionerWithdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'start', type: 'uint256' },
            { internalType: 'uint256', name: 'end', type: 'uint256' },
        ],
        name: 'distributePurchasedTokens',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'start', type: 'uint256' },
            { internalType: 'uint256', name: 'end', type: 'uint256' },
        ],
        name: 'distributeRefund',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'endTime', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'finalize', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'finishTime', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [],
        name: 'getAllInfo',
        outputs: [
            { internalType: 'address[5]', name: '', type: 'address[5]' },
            { internalType: 'uint256[7]', name: '', type: 'uint256[7]' },
            { internalType: 'bool', name: '', type: 'bool' },
            { internalType: 'string', name: '', type: 'string' },
            { internalType: 'enum Launchpad.State', name: '', type: 'uint8' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'getContributorCount', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [
            { internalType: 'uint256', name: 'start', type: 'uint256' },
            { internalType: 'uint256', name: 'end', type: 'uint256' },
        ],
        name: 'getContributors',
        outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'getState', outputs: [{ internalType: 'enum Launchpad.State', name: '', type: 'uint8' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [
            { internalType: 'uint256', name: 'start', type: 'uint256' },
            { internalType: 'uint256', name: 'end', type: 'uint256' },
        ],
        name: 'getWhiteList',
        outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'isBurnToken', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'isWithdraw', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'isWithdrawToken', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'lockSeconds', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'main', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'mainDecimals', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'maxCap', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'maxImum', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'minCap', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'minImum', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'owner', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'pool',
        outputs: [
            { internalType: 'uint256', name: 'balance', type: 'uint256' },
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'uint256', name: 'lockStart', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'presaleRate', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [{ internalType: 'address[]', name: '_usersAddresses', type: 'address[]' }],
        name: 'removeMultiWhitelistedUsers',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [
            { internalType: 'bool', name: '_useFomo', type: 'bool' },
            { internalType: 'uint8', name: '_FomoRate', type: 'uint8' },
        ],
        name: 'setFomo',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bool', name: '_useWhitelisting', type: 'bool' }],
        name: 'setUseWhitelisting',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'startTime', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'swapMain', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'swapToken', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'thisToken', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'token', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'tokenDecimals', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'totalClaimed', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'totalContribution', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'totalRefunded', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'uniswapV2Pair', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [{ internalType: 'address', name: 'pair', type: 'address' }], name: 'unlock', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'uint256[2]', name: '_capSettings', type: 'uint256[2]' }],
        name: 'updateCap',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256[2]', name: '_contributionSettings', type: 'uint256[2]' }],
        name: 'updateContribution',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'string', name: '_poolDetails', type: 'string' }],
        name: 'updatePoolDetails',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_presaleRate', type: 'uint256' }],
        name: 'updateRate',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256[2]', name: '_timeSettings', type: 'uint256[2]' }],
        name: 'updateTime',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: '_withdrawMainWallet', type: 'address' },
            { internalType: 'address', name: '_withdrawTokenWallet', type: 'address' },
        ],
        name: 'updateWithdrawAddress',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'useFomo', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'useWhitelisting', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'whitelisted',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'whitelistedNum', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'whitelistedUsers',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'withdraw', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'withdrawBase', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'withdrawCancel', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'withdrawFee', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'withdrawMainWallet', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [{ internalType: 'bool', name: 'isBurn', type: 'bool' }], name: 'withdrawToken', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'withdrawTokenWallet', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { stateMutability: 'payable', type: 'receive' }
];
